#pragma once

#include "pch.h"

// Generated by `yarn react-native codegen-windows` (see package.json's
// codegenConfig.windows). These two files are checked into source control so
// that the module can be built without running codegen first; regenerate them
// whenever src/NativeTwitterText.ts changes.
#include "codegen/NativeTwitterTextDataTypes.g.h"
#include "codegen/NativeTwitterTextSpec.g.h"

#include "NativeModules.h"

namespace winrt::TwitterText {

REACT_MODULE(TwitterTextModule, L"TwitterText")
struct TwitterTextModule {
    using ModuleSpec = TwitterTextCodegen::TwitterTextSpec;

    REACT_SYNC_METHOD(parseTweet)
    TwitterTextCodegen::ParseResults parseTweet(std::string text) noexcept;

    REACT_SYNC_METHOD(extractURLs)
    std::vector<TwitterTextCodegen::Entity> extractURLs(std::string text) noexcept;

    REACT_SYNC_METHOD(extractHashtags)
    std::vector<TwitterTextCodegen::Entity> extractHashtags(std::string text) noexcept;

    REACT_SYNC_METHOD(extractMentions)
    std::vector<TwitterTextCodegen::Entity> extractMentions(std::string text) noexcept;

    REACT_SYNC_METHOD(extractMentionsOrLists)
    std::vector<TwitterTextCodegen::Entity> extractMentionsOrLists(std::string text) noexcept;

    REACT_SYNC_METHOD(extractCashtags)
    std::vector<TwitterTextCodegen::Entity> extractCashtags(std::string text) noexcept;

    REACT_SYNC_METHOD(extractEntities)
    std::vector<TwitterTextCodegen::Entity> extractEntities(std::string text) noexcept;

    REACT_SYNC_METHOD(extractReplyScreenname)
    std::optional<std::string> extractReplyScreenname(std::string text) noexcept;

    REACT_SYNC_METHOD(isValidTweet)
    bool isValidTweet(std::string text) noexcept;

    REACT_SYNC_METHOD(isValidHashtag)
    bool isValidHashtag(std::string text) noexcept;

    REACT_SYNC_METHOD(tweetLength)
    double tweetLength(std::string text) noexcept;
};

} // namespace winrt::TwitterText
